Generate Server Code
sandboxnu/seitz pull request #100
Opened 2024-02-11 20:54 UTC by amberchow8

-Added short-unique-id library 
-Added middleware to Study schema where server code is generated when a Study is created in the database
-Changed server code to serverCode property of the Study on the StudyBuilderPage

2024-02-11 20:57 UTC, amberchow8 commented on packages/api/src/models/study.ts
> +    this.serverCode = uid.rnd(5);
Not sure if length of 5 is long enough

2024-02-21 00:54 UTC, ross3102 approved these changes
looks good! just small comments

2024-02-21 00:54 UTC, ross3102 commented on packages/ui/src/stores/studyBuilder.ts
> +      serverCode: serverCode.value!,
can this be undefined? curious why the `!`

2024-02-25 19:35 UTC, amberchow8 commented
I changed the pre middleware function a little to regenerate the server code if the first one generated is found in a study. I also added the alphanumeric lowercase dictionary for code generation so all letters are lowercase.

2024-02-25 19:40 UTC, ross3102 requested changes
all good except making sure the code generation never overlaps!

2024-02-25 19:40 UTC, ross3102 commented on packages/api/src/models/study.ts
> +      this.serverCode = uid.rnd(serverCodeLength);
good approach, but this will need to be a while loop of some kind in case the regenerated code is also taken

2024-02-25 19:57 UTC, ross3102 approved these changes
LGTM!

2024-02-25 20:19 UTC, merged