Created my studies page
sandboxnu/seitz pull request #50
Opened 2023-11-20 06:25 UTC by amberchow8

-Closes #44

2023-11-20 06:28 UTC, amberchow8 commented
Currently the page is displaying all the studies in the database by calling the /studies endpoint which returns all studies, but should we only get the studies from the current user?

2023-11-23 04:07 UTC, ross3102 requested changes
Left a few comments ranging from minor to major, lmk if you want to pair at some point or give it another shot :)

2023-11-23 04:07 UTC, ross3102 commented on packages/ui/src/pages/MyStudiesPage/MyStudiesPage.vue
> +            class="flex text-sm bg-neutral-300 border border-black rounded-lg py-1 w-30 p-4 h-8 justify-center"
Wow that's a lot of flex! (And fractional widths) You definitely don't need this much styling, and it has some pretty funky effects when you make the page smaller. Here's a few tips:
* If you have an element with `display: flex` that contains a single child element, you're probably doing something wrong i.e.
```
<div class="flex">
  <div ...>
    ...
  </div>
</div>
```
* See if you can do this layout without any `w-a/b`, you don't need it!
* Think about which elements should be a constant size (`w-n`), and which ones should grow/shrink when the page size changes (`flex-1`), that's what flex is great for!

2023-11-23 04:07 UTC, ross3102 commented on packages/ui/src/pages/MyStudiesPage/MyStudiesPage.vue
> +            class="flex text-sm bg-neutral-300 border border-black rounded-lg py-1 w-30 p-4 h-8 justify-center"
Happy to pair as well if you want

2023-11-23 04:07 UTC, ross3102 commented on packages/ui/src/pages/MyStudiesPage/components/StudyComponent.vue
> +    <div class="flex flex-row my-20 justify-left w-4/5 self-center">
`my-20` that is a lot of margin (80px) lol, is this needed?

2023-11-23 04:07 UTC, ross3102 commented on packages/ui/src/pages/MyStudiesPage/components/StudyComponent.vue
> +    <div class="flex flex-row my-20 justify-left w-4/5 self-center">
Same as above, this flex row inside a flex row is a red flag, also `flex-row` is the default behavior for flex anyway so you never need it :)

2023-11-27 23:42 UTC, ross3102 approved these changes

2023-11-27 23:42 UTC, merged